name: Fetch Blog JSON

on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  fetch-blog-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install httpx

      - name: Fetch and save blog JSON
        run: |
          python -m scripts.sync \
          --url 'https://rednafi.com/index.json' --output 'data/index.json'

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes_detected=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes_detected == 'true'
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add data/index.json
          git commit -m "Update index.json"
          git push

      - name: Print no changes message
        if: steps.git-check.outputs.changes_detected != 'true'
        run: echo "No changes detected. Skipping commit."
